### ISSUE TITLE
feat: additional information output while using `Deploy-NAVApp`

### ISSUE THREAD

**Issue by lukas-pfeifhofer** [EOS-Solutions/Gordon#244]
# 🙋 Feature Request

The `Deploy-NAVApp` give some information about the Apps installed, it would be helpful to show the feed where the installed App was found.

## 🤔 Expected Behavior

Show the source feed on the installed App summary list.

## 💻 Examples

```YAML
AppId                 : b2dd1d81-3e95-46a8-94ef-8c32d872bf0c
Id                    : b2dd1d81-3e95-46a8-94ef-8c32d872bf0c
AlternateIds          : {}
Publisher             : EOS Solutions
Name                  : Advanced Document Reporting
Version               : 20.0.0.0
HasId                 : True
HasVersion            : True
MinApplicationVersion : 
MinPlatformVersion    : 
Feed                  :  https://pkgs.dev.azure.com/EosSolutionsPublic/Eos.Apps.internal/_packaging/xtpublisher/nuget/v3/index.json
```

## Product
- [ ] Gordon (Version: _WriteHereTheVersion_)
- [ ] Gordon VSCode (Version: _WriteHereTheVersion_)
- [*] Gordon Powershell (Version: for any up-coming version)
- [ ] Gordon Service (Version: _WriteHereTheVersion_)
- [ ] Gordon Xliff Editor
- [ ] EOS Gordon Installer
